language: cpp

compiler:
  - g++
  - clang
  
os:
  - linux
  - osx
  
matrix:
  exclude:
    - os: osx 
      compiler: g++

env:
  - OMP_NUM_THREADS=2

before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:boost-latest/ppa; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:kubuntu-ppa/backports; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo add-apt-repository -y ppa:roblib/ppa; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.7 main' >> /etc/apt/sources.list"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install cmake; fi 
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo "$CXX"; fi 
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then  if [ "$CXX" == "g++" ]; then sudo apt-get install g++-4.8; export CXX="g++-4.8"; fi; fi 
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then  if [ "$CXX" == "clang++" ]; then sudo apt-get --force-yes install clang-3.7; export CXX="clang++-3.7"; fi; fi 
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libboost1.55-dev  libboost-date-time1.55-dev libboost-filesystem1.55-dev; fi 
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libboost-graph1.55-dev libboost-iostreams1.55-dev libboost-math1.55-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libboost-program-options1.55-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libboost-random1.55-dev libboost-regex1.55-dev libboost-serialization1.55-dev; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install libboost-system1.55-dev libboost-test1.55-dev libboost-thread1.55-dev; fi
  - if [ "$TRAVIS_OS_NAME" != "linux" ]; then brew update && brew unlink cmake && brew install cmake; fi
  
before_script:  
  - mkdir build
  - cd build
  - cmake ..
  
script:
  - make -j3 && make test