# specify platforms
platform: 
  - Win32
  - x64  

# configuration
configuration: 
#  - Debug
  - Release

# set environment variables
environment:
  BOOST_ROOT: C:\Libraries\boost
  #OMP_NUM_THREADS: 2

# specify branch
branches:
  only:
    - master
  
# before everything
init:
  - cmd: cmake --version
  - cmd: msbuild /version
  #- cmd: dir %BOOST_LIBRARYDIR%

# clone directory
clone_folder: C:\projects\shark

# scripts to run before build
before_build:
  - cmd: cd C:\projects\shark
  #- cmd: dir 
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=Visual Studio 14
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=Visual Studio 14 Win64
  - cmd: if "%platform%"=="Win32" set BOOST_LIBRARYDIR=%BOOST_ROOT%\lib32-msvc-14.0
  - cmd: if "%platform%"=="x64"   set BOOST_LIBRARYDIR=%BOOST_ROOT%\lib64-msvc-14.0

  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" -DCMAKE_BUILD_TYPE=%configuration% -DBUILD_TESTING=OFF -DBUILD_SHARED_LIBS=ON -DBUILD_EXAMPLES=OFF -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%"   ..
  #- cmd: type C:\projects\shark\build\shark.sln 
  
# actual build process
build:
  project: C:\projects\shark\build\shark.sln 
  parallel: true 
  verbosity: minimal # compiler verbosity
